services:
  reverse-proxy-nginx:
    image: nginx:alpine-slim
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # This certificate expires on 2025-12-13
      - ./certs:/etc/letsencrypt:ro
  wedding-app:
    image: wedding-app:1.0
    environment:
      TZ: ${TZ}
      PORT: ${PORT}
      HOST: ${HOST}
      LOG_LEVEL: ${LOG_LEVEL}
      APP_KEY: ${APP_KEY}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./wedding.sqlite:/persistent/data/wedding.sqlite
    ports:
      - "3333:3333"
