services:
  reverse-proxy-nginx:
    image: nginx:alpine-slim
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - nginx.conf:/etc/nginx/conf.d/default.conf
      # This certificate expires on 2025-12-13
      - /etc/letsencrypt/live/bodaandrestamara.space:/etc/letsencrypt
  wedding-app:
    image: wedding-app:1.0
    ports:
      - "3333:3333"
